# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\"p\n\x08\x45mployee\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12)\n\remployee_type\x18\x04 \x01(\x0e\x32\r.EmployeeTypeH\x00\x88\x01\x01\x42\x10\n\x0e_employee_type\")\n\tEmployees\x12\x1c\n\temployees\x18\x01 \x03(\x0b\x32\t.Employee*F\n\x0c\x45mployeeType\x12\r\n\tFULL_TIME\x10\x00\x12\r\n\tPART_TIME\x10\x01\x12\x0c\n\x08\x43ONTRACT\x10\x02\x12\n\n\x06INTERN\x10\x03\x62\x06proto3')

_EMPLOYEETYPE = DESCRIPTOR.enum_types_by_name['EmployeeType']
EmployeeType = enum_type_wrapper.EnumTypeWrapper(_EMPLOYEETYPE)
FULL_TIME = 0
PART_TIME = 1
CONTRACT = 2
INTERN = 3


_EMPLOYEE = DESCRIPTOR.message_types_by_name['Employee']
_EMPLOYEES = DESCRIPTOR.message_types_by_name['Employees']
Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEE,
  '__module__' : 'employee_pb2'
  # @@protoc_insertion_point(class_scope:Employee)
  })
_sym_db.RegisterMessage(Employee)

Employees = _reflection.GeneratedProtocolMessageType('Employees', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEES,
  '__module__' : 'employee_pb2'
  # @@protoc_insertion_point(class_scope:Employees)
  })
_sym_db.RegisterMessage(Employees)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPLOYEETYPE._serialized_start=175
  _EMPLOYEETYPE._serialized_end=245
  _EMPLOYEE._serialized_start=18
  _EMPLOYEE._serialized_end=130
  _EMPLOYEES._serialized_start=132
  _EMPLOYEES._serialized_end=173
# @@protoc_insertion_point(module_scope)
